### ISSUE TITLE
Rename placeholder "add Bitcoin address" to "search for Bitcoin address"

### ISSUE THREAD

**Issue by Sajjon** [radixdlt/mtps#4]
I think the placeholder of the search field `"add Bitcoin address"` can have a better phrasing, maybe `"Search for a Bitcoin address"`

**Comment by MuncleUscles** [comment]
And if we're saying "Watch", then it should auto-update, or change the button text

**Comment by blenessy** [comment]
Refrase "Watch" too + check final solution with stakeholder.
