### ISSUE TITLE
Discover when to transition to state 'FINISHED' instead of hardcoded 60mins.

### ISSUE THREAD

**Issue by swiec** [radixdlt/mtps#48]
At the moment we are having hardcoded 60 minutes for the test-run, back-end should discover when the test is really finished. 

https://github.com/radixdlt/mtps/blob/master/explorer/service/src/main/java/org/radixdlt/explorer/system/TestStateProvider.java#L185

**Comment by blenessy** [comment]
confirmed fixed and deployed.
