### ISSUE TITLE
Explorer: the little "H" under the hour counter has the wrong offset

### ISSUE THREAD

**Issue by blenessy** [radixdlt/mtps#49]
![image](https://user-images.githubusercontent.com/5358256/59771882-f8eeb580-92aa-11e9-8203-5e6f7073c7a6.png)

**Comment by laszlourszuly** [comment]
It turns out that offset is a hard-coded value which doesn't honour the number of "hour flips". If adjusting for two "flips" it will look bad when we have three "flips" instead. I recommend we accept this minor graphical glitch and learn to live with it.
