### ISSUE TITLE
If explorer is not manually refreshed during the test run, progress bar shows 100% constantly

### ISSUE THREAD

**Issue by swiec** [radixdlt/mtps#72]
As title says,
during the test if the progress bar is not refreshed manually (e.g. by hitting F5) the progress bar show 100% constantly (attached screenshot, with refreshed explorer tab on the right)
![Screenshot 2019-06-25 at 23 06 29](https://user-images.githubusercontent.com/2485271/60133706-29988880-979e-11e9-9efb-e9fb84dbf5c2.png)

**Comment by laszlourszuly** [comment]
Fix implemented, pending review (#73)
