### ISSUE TITLE
Need to move start trigger to AtomPump.java

### ISSUE THREAD

**Issue by blenessy** [radixdlt/mtps#76]
Currently an [external process](https://github.com/radixdlt/node-runner/blob/mtps/docker/radixdlt-core/docker-entrypoint.sh#L111-L118) (shell script) uses the `sleep` command to schedule test runs. The pumping is kicked off when the `sleep` command times out and the script in question continues to a create a `/opt/radixdlt/START_PUMP` file. The AtomPump thread in Java monitors the file system and will start pumping as soon as the `START_PUMP` file shows up.

# Change Request

(https://github.com/radixdlt/node-runner/blob/mtps/docker/radixdlt-core/docker-entrypoint.sh#L111-L118) script.
- [x] Change the AtomPump.java code to read the scheduled timestamp from https://test.radixdlt.com/api/metrics
- [x] AtomPump.java should detect change on https://test.radixdlt.com/api/metrics (poll every minute)
- [x] AtomPump.java should be able to poll a different URL than https://test.radixdlt.com/api/metrics, though configuration (env var).
- [x] Get rid of the START_PUMP scheduling in the [docker-entrypoint.sh]

**Comment by x-wf** [comment]
**RadixCore**
https://duskendale.dev.radixdlt.com/coredevs/RadixCore/merge_requests/197/diffs

**node-runner**
https://github.com/radixdlt/node-runner/commit/28752dd4ac28be2057fc4d6859d83cc44de6544e
