### ISSUE TITLE
BTC transaction explorer styling is broken on smaller devices

### ISSUE THREAD

**Issue by MuncleUscles** [radixdlt/mtps#8]
![Screenshot 2019-06-12 at 14 37 31](https://user-images.githubusercontent.com/2372232/59364358-a5222080-8d2e-11e9-9a4a-52383d552c73.png)

**Comment by MuncleUscles** [comment]
And so is the comparison box

![Screenshot 2019-06-13 at 13 33 33](https://user-images.githubusercontent.com/2372232/59433047-94ca7e00-8de0-11e9-80fb-7b5d0d32fdd6.png)

**Comment by blenessy** [comment]
Lots of effort to implement proper solution for this ... will revisit later.

**Comment by blenessy** [comment]
Investigating visitor data to understand the significance of this one.

**Comment by blenessy** [comment]
approx. 50% of all visitors are mobile, so this is very bad. Prioritising.
